name: Cleanup

on:
  schedule:
    - cron: '0 1 * * 0' # Run every Sunday at 1 AM
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Clean up old artifacts
      uses: actions/github-script@v7
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 30); // Keep artifacts for 30 days
          
          for (const artifact of artifacts.data.artifacts) {
            const createdAt = new Date(artifact.created_at);
            if (createdAt < cutoffDate) {
              console.log(`Deleting old artifact: ${artifact.name}`);
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
            }
          }
          
    - name: Clean up old releases
      uses: actions/github-script@v7
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 90); // Keep releases for 90 days
          
          for (const release of releases.data) {
            const createdAt = new Date(release.created_at);
            if (createdAt < cutoffDate && !release.draft) {
              console.log(`Deleting old release: ${release.tag_name}`);
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id
              });
            }
          }
          
    - name: Clean up old branches
      uses: actions/github-script@v7
      with:
        script: |
          const branches = await github.rest.repos.listBranches({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 30); // Keep branches for 30 days
          
          for (const branch of branches.data) {
            if (branch.name === 'main' || branch.name === 'develop') {
              continue; // Don't delete main branches
            }
            
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: branch.name
            });
            
            const lastCommitDate = new Date(commit.data.commit.committer.date);
            if (lastCommitDate < cutoffDate) {
              console.log(`Deleting old branch: ${branch.name}`);
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch.name}`
              });
            }
          }
          
    - name: Clean up old issues
      uses: actions/github-script@v7
      with:
        script: |
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed',
            sort: 'updated',
            direction: 'desc'
          });
          
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 180); // Keep closed issues for 180 days
          
          for (const issue of issues.data) {
            if (issue.pull_request) {
              continue; // Don't delete PRs
            }
            
            const updatedAt = new Date(issue.updated_at);
            if (updatedAt < cutoffDate) {
              console.log(`Closing old issue: ${issue.number}`);
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
          }
          
    - name: Clean up old pull requests
      uses: actions/github-script@v7
      with:
        script: |
          const pulls = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed',
            sort: 'updated',
            direction: 'desc'
          });
          
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 90); // Keep closed PRs for 90 days
          
          for (const pull of pulls.data) {
            const updatedAt = new Date(pull.updated_at);
            if (updatedAt < cutoffDate) {
              console.log(`Closing old PR: ${pull.number}`);
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull.number,
                state: 'closed'
              });
            }
          }
          
    - name: Clean up old workflow runs
      uses: actions/github-script@v7
      with:
        script: |
          const workflows = await github.rest.actions.listWorkflows({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 30); // Keep workflow runs for 30 days
          
          for (const workflow of workflows.data.workflows) {
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
              status: 'completed'
            });
            
            for (const run of runs.data.workflow_runs) {
              const createdAt = new Date(run.created_at);
              if (createdAt < cutoffDate) {
                console.log(`Deleting old workflow run: ${run.id}`);
                await github.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id
                });
              }
            }
          }
          
    - name: Create cleanup report
      run: |
        echo "# Cleanup Report - $(date)" > cleanup-report.md
        echo "" >> cleanup-report.md
        echo "## Cleaned Up" >> cleanup-report.md
        echo "- Old artifacts (30+ days)" >> cleanup-report.md
        echo "- Old releases (90+ days)" >> cleanup-report.md
        echo "- Old branches (30+ days)" >> cleanup-report.md
        echo "- Old issues (180+ days)" >> cleanup-report.md
        echo "- Old pull requests (90+ days)" >> cleanup-report.md
        echo "- Old workflow runs (30+ days)" >> cleanup-report.md
        echo "" >> cleanup-report.md
        echo "## Timestamp" >> cleanup-report.md
        echo "$(date)" >> cleanup-report.md
        
    - name: Upload cleanup report
      uses: actions/upload-artifact@v4
      with:
        name: cleanup-report-$(date +%Y%m%d)
        path: cleanup-report.md